### ISSUE TITLE
Missing Test Set Annotations

### ISSUE THREAD

**Issue by liujunzhuo** [shuheikurita/RefEgo#2]
I've been using the RefEgo dataset for my research, and I noticed that the GitHub repository provides annotations for the train and val sets. However, the README and the associated paper mention the availability of a test set, but I couldn't locate the test set annotations in the repository.

I'm keen to access the test set annotations for a thorough evaluation. Thank you for your time and assistance in addressing this issue, and your support is greatly appreciated.

**Comment by shuheikurita** [comment]
Sorry for the late reply.
We have just include the test split in FPS2 in the RefEgoAnnotations.zip.
You can download it from https://refegopublic.s3.amazonaws.com/RefEgoAnnotations.zip
