### ISSUE TITLE
Extracted images do not match provided bounding box annotations

### ISSUE THREAD

**Issue by liujunzhuo** [shuheikurita/RefEgo#3]
**Issue Description:**
- Extracted images do not match provided bounding box annotations. For example: I'm using the following ffmpeg command to extract images from 57e88d87-257e-434d-953e-6025367e99fe.mp4:
```sh
ffmpeg -hwaccel cuda -i "ego4d/v1/full_scale/57e88d87-257e-434d-953e-6025367e99fe.mp4" -vf "fps=2,scale=640:-1" -qscale 1 "refego/57e88d87-257e-434d-953e-6025367e99fe/img%10d.jpg"
```
- However, **the extracted images do not align with the provided bounding box annotations**, as illustrated in this example: ![Example](https://github.com/shuheikurita/RefEgo/assets/44314723/4933c9c0-a26c-45de-af9a-33379b687bca)
- The code I'm using to extract bounding box annotations is as follows:
```python
from PIL import Image, ImageDraw, ImageFont
from matplotlib import pyplot as plt
from pycocotools.coco import COCO

anno = COCO(anno_path)
target = anno.loadAnns(anno.getAnnIds(i))[0]
img = anno.loadImgs(i)[0]
image_path= os.path.join(data_path, img["file_name"])
caption = img["caption"]
bbox = target["bbox"] if anno.loadAnns(anno.getAnnIds(i))[0]["is_obj_in"] else [0, 0, 0, 0]
bbox = xywh_to_xyxy(bbox)
image_pil = Image.open(image_path).convert("RGB")
plot_boxes_to_image(image_pil, bbox)

def xywh_to_xyxy(box):
    x, y, w, h = box
    x1 = x
    y1 = y
    x2 = x + w
    y2 = y + h
    return [x1, y1, x2, y2]
```

- I've tested multiple ffmpeg versions, including:
  - 7:6.0-9ubuntu1
  - 7:4.2.7-0ubuntu0.1
  - 7:4.2.2-1ubuntu1
  - 7:3.4.11-0ubuntu0.1
- **The extracted images remain the same** across multiple ffmpeg versions and with or without the `-hwaccel cuda` option.

**Environment Information:**
- My environment: Ubuntu 20.04.3 LTS with CUDA 11.8.
- I also tried the provided Docker environment, and the issue remains unresolved.

Could you specify the correct ffmpeg version and provide the precise parameters I should use for image extraction. Additionally, I would greatly appreciate it if you could kindly confirm whether my code for extracting bounding box annotations is correct. Thank you.

**Comment by ZJWang9928** [comment]
Hello, I came across the same problem with you. Have you solved it yet?

**Comment by liujunzhuo** [comment]
> Hello, I came across the same problem with you. Have you solved it yet?

sadly, no

**Comment by ZJWang9928** [comment]
Then are you still directly using this dataset for research or using other ones currently?

**Comment by shuheikurita** [comment]
We sincerely appreciate having interests on RefEgo!

We check the data and code and it seems that this seems due to the annotations derived from MTurk. Given that the annotations were done through MTurk, such problems are somewhat inevitable. However we are considering whether we can release a revised version for annotations.

**Comment by liujunzhuo** [comment]
Thank you for your response. I have write a comprehensive reproduction process in issue #5.
