### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by yahooo-m** [shuheikurita/RefEgo#4]
Hi, how can I download the video datasets of ego4d? all of them?

**Comment by ZJWang9928** [comment]
Same question. It's quite slow and unsteady even if we can use u_id to specify the video used in RefEgo with aws-cli when downloading ego4D. It will be much more convenient if the author of RefEgo can provide the used video data with cloud drive.

**Comment by shuheikurita** [comment]
Hi! Thank you for having interests in RefEgo dataset!

We add automated scripts for RefEgo preprocessing: https://github.com/shuheikurita/RefEgo/blob/main/dataset/README.md
You can also see the list of videos used in RefEgo here: https://github.com/shuheikurita/RefEgo/blob/main/dataset/video_list.txt
You don't need to download all of Ego4D videos!

Unfortunately, we consider that we cannot release images of RefEgo directly, but we prepare a conversion script from Ego4D videos. If you still encounter problems in data preprocessing, please directly email to me (written in the paper)...
